name: Compile blocklist

on:
  push:
  schedule:
    - cron: "0 2 * * *"

jobs:
  optimize-and-commit-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: diff before
        run: git diff --quiet

      - name: Optimize
        run: ./build.sh

      - name: DIFF
        run: git diff --quiet

      - name: Commit
        run: |
          git diff --quiet
          if ! git diff --quiet; then
            echo "nothing to commit, working tree clean"
          else
            echo "commit..."
            git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
            git config --global user.name github-actions[bot]
            git add .
            git commit -m "optimize"
          fi
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
