name: Compile blocklist

on:
  push:

jobs:
  optimize-and-commit-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Optimize
      run: ./build.sh
    - name: Commit
      run: |
        status_log=$(git status -sb)
        if [ "$status_log" == "## main...origin/main" ];then
          echo "nothing to commit, working tree clean"
        else
          echo "commit..."
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "optimize" -a
        fi
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        force: true