name: Compile blocklist

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  optimize-and-commit-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Optimize
        run: ./build.sh

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git diff --quiet && exit 0
          git add .
          git commit -m "optimize $(date)"
          git push origin HEAD:${{ github.ref_name }}
